import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shyam Kaushik
 */
public class Telecom extends javax.swing.JFrame {

    /**
     * Creates new form Telecom
     */
    public Telecom() {
        initComponents();
    }
    String username = "";
    String pswd = "";
    String username1 = "";
    String pswd1 = "";
    String fname = "";
    String lname = "";
    String ssn;
    String email = "";
    String password = "";
    String cpassword = "";
    String phno;
    String company_name = "";
    String plan_id;
    int uid;
    String suid = "";
    String add1 = "";
    String add2 = "";
    String add3 = "";
    String pincode;
    String city = "";
    String altphno;
    String email_add = "";
    String date = "";
    String month = "";
    String year = "";
    String company = "";
    String pack_name = "";
    String company_name1 = "";
    String company1 = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jFrame3 = new javax.swing.JFrame();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame5 = new javax.swing.JFrame();
        jLabel29 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        jTextField10 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jFrame6 = new javax.swing.JFrame();
        jLabel37 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jFrame4 = new javax.swing.JFrame();
        jLabel34 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField18 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jFrame7 = new javax.swing.JFrame();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jComboBox7 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jFrame1.setMinimumSize(new java.awt.Dimension(630, 511));
        jFrame1.getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 2, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LogIn Page");
        jFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 20, 250, 67);

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username :");
        jFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 190, 90, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 190, 400, 40);

        jLabel8.setFont(new java.awt.Font("Bodoni MT", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password :");
        jFrame1.getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 250, 100, 50);
        jFrame1.getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(140, 260, 400, 40);

        jButton3.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jButton3.setText("LogIn");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(140, 370, 150, 50);

        jButton9.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton9);
        jButton9.setBounds(390, 370, 150, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shyam Kaushik\\Pictures\\backgroung\\dark bg with stars.png")); // NOI18N
        jFrame1.getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 630, 510);

        jFrame2.setMinimumSize(new java.awt.Dimension(688, 723));
        jFrame2.getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 2, 48)); // NOI18N
        jLabel9.setText("SignIn Page");
        jFrame2.getContentPane().add(jLabel9);
        jLabel9.setBounds(180, 40, 270, 80);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel10.setText("First name");
        jFrame2.getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 170, 100, 30);

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel12.setText("Last name");
        jFrame2.getContentPane().add(jLabel12);
        jLabel12.setBounds(80, 220, 110, 30);

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel13.setText("email address");
        jFrame2.getContentPane().add(jLabel13);
        jLabel13.setBounds(80, 320, 107, 30);

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel14.setText("New password");
        jFrame2.getContentPane().add(jLabel14);
        jLabel14.setBounds(80, 370, 140, 30);

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel15.setText("confirm password");
        jFrame2.getContentPane().add(jLabel15);
        jLabel15.setBounds(80, 420, 150, 30);

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel16.setText("Mobile number");
        jFrame2.getContentPane().add(jLabel16);
        jLabel16.setBounds(80, 480, 130, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jTextField2);
        jTextField2.setBounds(250, 170, 240, 30);
        jFrame2.getContentPane().add(jTextField4);
        jTextField4.setBounds(250, 220, 240, 30);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jTextField5);
        jTextField5.setBounds(250, 320, 240, 30);

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(250, 370, 240, 30);
        jFrame2.getContentPane().add(jPasswordField3);
        jPasswordField3.setBounds(250, 420, 240, 30);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jTextField6);
        jTextField6.setBounds(280, 480, 210, 30);

        jButton4.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jButton4.setText("Continue");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jButton4);
        jButton4.setBounds(120, 580, 200, 60);

        jButton10.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jButton10.setText("Go Back");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jButton10);
        jButton10.setBounds(350, 580, 200, 60);

        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel23.setText("SSN");
        jFrame2.getContentPane().add(jLabel23);
        jLabel23.setBounds(80, 270, 32, 30);
        jFrame2.getContentPane().add(jTextField21);
        jTextField21.setBounds(250, 270, 240, 30);

        jLabel18.setText("+91");
        jFrame2.getContentPane().add(jLabel18);
        jLabel18.setBounds(250, 480, 48, 30);

        jLabel19.setText("8 digit unique number");
        jFrame2.getContentPane().add(jLabel19);
        jLabel19.setBounds(260, 300, 140, 16);

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shyam Kaushik\\Pictures\\backgroung\\bluish-flare-powerpoint-templates.jpg")); // NOI18N
        jLabel21.setText("month");
        jFrame2.getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 0, 690, 730);

        jFrame3.setMinimumSize(new java.awt.Dimension(656, 536));
        jFrame3.getContentPane().setLayout(null);

        jLabel22.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel22.setText("Welcome");
        jFrame3.getContentPane().add(jLabel22);
        jLabel22.setBounds(170, 20, 280, 60);

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel25.setText("select from the following choices");
        jFrame3.getContentPane().add(jLabel25);
        jLabel25.setBounds(180, 230, 300, 40);

        jLabel26.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel26.setText("To the");
        jFrame3.getContentPane().add(jLabel26);
        jLabel26.setBounds(360, 10, 200, 80);

        jLabel27.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel27.setText("Sim Card Section");
        jFrame3.getContentPane().add(jLabel27);
        jLabel27.setBounds(160, 70, 370, 80);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setText("Apply for new Sim");
        jFrame3.getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(180, 290, 160, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setText("Converting a Sim");
        jFrame3.getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(180, 320, 160, 25);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton3.setText("View Trends among companies");
        jFrame3.getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(180, 350, 250, 25);

        jButton6.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jButton6.setText("Continue");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(jButton6);
        jButton6.setBounds(20, 420, 180, 60);

        jButton7.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(jButton7);
        jButton7.setBounds(220, 420, 180, 60);

        jButton13.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jButton13.setText("Exit");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(jButton13);
        jButton13.setBounds(420, 420, 170, 60);

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shyam Kaushik\\Pictures\\backgroung\\white-wallpapers-collection-40.jpg")); // NOI18N
        jLabel28.setMaximumSize(new java.awt.Dimension(656, 568));
        jLabel28.setMinimumSize(new java.awt.Dimension(656, 568));
        jLabel28.setPreferredSize(new java.awt.Dimension(656, 568));
        jFrame3.getContentPane().add(jLabel28);
        jLabel28.setBounds(0, 0, 656, 540);

        jFrame5.setMinimumSize(new java.awt.Dimension(750, 817));
        jFrame5.getContentPane().setLayout(null);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Select the company");
        jFrame5.getContentPane().add(jLabel29);
        jLabel29.setBounds(10, 10, 150, 40);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Airtel", "Jio", "Vodaphone", "Idea", "Docomo" }));
        jFrame5.getContentPane().add(jComboBox1);
        jComboBox1.setBounds(10, 50, 160, 40);

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTable1.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plan Id", "Package Name", "Price", "FUP", "Upload", "Download"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setMaximumSize(new java.awt.Dimension(560, 160));
        jTable1.setMinimumSize(new java.awt.Dimension(560, 160));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(60);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(1).setMinWidth(200);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        jFrame5.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 700, 230);
        jFrame5.getContentPane().add(jScrollBar1);
        jScrollBar1.setBounds(710, 0, 21, 770);

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jFrame5.getContentPane().add(jTextField10);
        jTextField10.setBounds(100, 430, 150, 40);

        jLabel30.setText("First Name");
        jFrame5.getContentPane().add(jLabel30);
        jLabel30.setBounds(20, 440, 62, 16);

        jLabel32.setText("Last Name");
        jFrame5.getContentPane().add(jLabel32);
        jLabel32.setBounds(270, 440, 70, 16);
        jFrame5.getContentPane().add(jTextField11);
        jTextField11.setBounds(350, 430, 150, 40);

        jLabel33.setText("Plan ID");
        jFrame5.getContentPane().add(jLabel33);
        jLabel33.setBounds(30, 540, 50, 16);
        jFrame5.getContentPane().add(jTextField12);
        jTextField12.setBounds(130, 530, 90, 30);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setText("Fill in your details");
        jFrame5.getContentPane().add(jLabel35);
        jLabel35.setBounds(20, 380, 180, 30);

        jButton14.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jButton14.setText("Continue");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jFrame5.getContentPane().add(jButton14);
        jButton14.setBounds(20, 670, 210, 60);

        jButton15.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jButton15.setText("Back");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jFrame5.getContentPane().add(jButton15);
        jButton15.setBounds(240, 670, 240, 60);

        jButton16.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jButton16.setText("Exit");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jFrame5.getContentPane().add(jButton16);
        jButton16.setBounds(490, 670, 200, 60);

        jLabel36.setText("Service Provider");
        jFrame5.getContentPane().add(jLabel36);
        jLabel36.setBounds(30, 620, 100, 16);

        jTextField13.setEditable(false);
        jFrame5.getContentPane().add(jTextField13);
        jTextField13.setBounds(130, 610, 170, 30);

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton20.setText("Show plans");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jFrame5.getContentPane().add(jButton20);
        jButton20.setBounds(10, 110, 120, 25);

        jFrame6.setMinimumSize(new java.awt.Dimension(698, 628));
        jFrame6.getContentPane().setLayout(null);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("provide the address for the delivery of the sim");
        jFrame6.getContentPane().add(jLabel37);
        jLabel37.setBounds(20, 40, 330, 20);
        jFrame6.getContentPane().add(jTextField14);
        jTextField14.setBounds(80, 72, 320, 30);
        jFrame6.getContentPane().add(jTextField15);
        jTextField15.setBounds(80, 102, 320, 30);
        jFrame6.getContentPane().add(jTextField16);
        jTextField16.setBounds(80, 132, 320, 30);

        jLabel38.setText("line 1");
        jFrame6.getContentPane().add(jLabel38);
        jLabel38.setBounds(20, 80, 31, 16);

        jLabel39.setText("line 2");
        jFrame6.getContentPane().add(jLabel39);
        jLabel39.setBounds(20, 110, 48, 16);

        jLabel40.setText("line 3");
        jFrame6.getContentPane().add(jLabel40);
        jLabel40.setBounds(20, 140, 31, 16);

        jLabel41.setText("pincode");
        jFrame6.getContentPane().add(jLabel41);
        jLabel41.setBounds(20, 190, 44, 16);
        jFrame6.getContentPane().add(jTextField17);
        jTextField17.setBounds(80, 180, 110, 30);

        jLabel42.setText("city");
        jFrame6.getContentPane().add(jLabel42);
        jLabel42.setBounds(20, 230, 19, 16);

        jLabel43.setText("State");
        jFrame6.getContentPane().add(jLabel43);
        jLabel43.setBounds(20, 270, 30, 16);

        jTextField19.setEditable(false);
        jTextField19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField19.setText("KARNATAKA");
        jFrame6.getContentPane().add(jTextField19);
        jTextField19.setBounds(80, 260, 190, 30);

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setText("Other customer details");
        jFrame6.getContentPane().add(jLabel44);
        jLabel44.setBounds(20, 300, 170, 20);

        jLabel45.setText("E-mail address");
        jFrame6.getContentPane().add(jLabel45);
        jLabel45.setBounds(20, 370, 100, 16);
        jFrame6.getContentPane().add(jTextField20);
        jTextField20.setBounds(120, 360, 360, 30);

        jButton17.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jButton17.setText("Confirm");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jFrame6.getContentPane().add(jButton17);
        jButton17.setBounds(30, 510, 210, 50);

        jButton18.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jButton18.setText("Back");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jFrame6.getContentPane().add(jButton18);
        jButton18.setBounds(260, 510, 200, 50);

        jButton19.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jButton19.setText("Exit");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jFrame6.getContentPane().add(jButton19);
        jButton19.setBounds(490, 510, 180, 50);

        jLabel11.setText("Alternate phone number");
        jFrame6.getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 330, 150, 16);

        jLabel20.setText("+91");
        jFrame6.getContentPane().add(jLabel20);
        jLabel20.setBounds(190, 330, 30, 16);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jFrame6.getContentPane().add(jTextField3);
        jTextField3.setBounds(220, 320, 200, 30);

        jLabel17.setText("Date of Birth");
        jFrame6.getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 430, 80, 16);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DATE", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jFrame6.getContentPane().add(jComboBox3);
        jComboBox3.setBounds(130, 422, 80, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MONTH", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jFrame6.getContentPane().add(jComboBox4);
        jComboBox4.setBounds(220, 422, 80, 30);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YEAR", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010" }));
        jFrame6.getContentPane().add(jComboBox5);
        jComboBox5.setBounds(310, 420, 80, 30);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Ballari", "Bangaluru", "Belagavi", "Chikkamagaluru", "Hosapete", "Hubli", "Kalaburagi", "Mangaluru", "Mysuru", "Shivamogga", "Tumkur ", "Vijapur", " " }));
        jFrame6.getContentPane().add(jComboBox6);
        jComboBox6.setBounds(80, 222, 190, 30);

        jFrame4.setMaximumSize(new java.awt.Dimension(750, 817));
        jFrame4.setMinimumSize(new java.awt.Dimension(750, 817));
        jFrame4.setPreferredSize(new java.awt.Dimension(750, 817));
        jFrame4.getContentPane().setLayout(null);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("Select the company");
        jFrame4.getContentPane().add(jLabel34);
        jLabel34.setBounds(10, 0, 150, 40);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Airtel", "Jio", "Vodaphone", "Idea", "BSNL" }));
        jFrame4.getContentPane().add(jComboBox2);
        jComboBox2.setBounds(10, 40, 160, 40);

        jTable2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTable2.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Plan Id", "Package Name", "Price", "FUP", "Upload", "Download"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setMaximumSize(new java.awt.Dimension(560, 160));
        jTable2.setMinimumSize(new java.awt.Dimension(560, 160));
        jTable2.setRowHeight(20);
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(60);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(60);
            jTable2.getColumnModel().getColumn(1).setMinWidth(200);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        jFrame4.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 120, 720, 230);

        jLabel24.setText("Enter your UId");
        jFrame4.getContentPane().add(jLabel24);
        jLabel24.setBounds(20, 390, 90, 16);
        jFrame4.getContentPane().add(jTextField7);
        jTextField7.setBounds(120, 382, 110, 30);

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setText("User Details");
        jFrame4.getContentPane().add(jLabel46);
        jLabel46.setBounds(20, 430, 100, 20);

        jLabel47.setText("First name");
        jFrame4.getContentPane().add(jLabel47);
        jLabel47.setBounds(20, 470, 70, 16);

        jTextField8.setEditable(false);
        jFrame4.getContentPane().add(jTextField8);
        jTextField8.setBounds(100, 460, 150, 30);

        jLabel48.setText("Last name");
        jFrame4.getContentPane().add(jLabel48);
        jLabel48.setBounds(20, 510, 70, 16);

        jTextField9.setEditable(false);
        jFrame4.getContentPane().add(jTextField9);
        jTextField9.setBounds(100, 500, 150, 30);

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setText("Current Plan Details");
        jFrame4.getContentPane().add(jLabel49);
        jLabel49.setBounds(310, 430, 160, 17);

        jLabel50.setText("Plan ID");
        jFrame4.getContentPane().add(jLabel50);
        jLabel50.setBounds(310, 470, 40, 16);

        jTextField22.setEditable(false);
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jTextField22);
        jTextField22.setBounds(420, 460, 100, 30);

        jLabel51.setText("Plan description");
        jFrame4.getContentPane().add(jLabel51);
        jLabel51.setBounds(310, 510, 100, 16);

        jLabel52.setText("Enter new Plan ID");
        jFrame4.getContentPane().add(jLabel52);
        jLabel52.setBounds(20, 610, 150, 16);

        jLabel53.setText("New service provider");
        jFrame4.getContentPane().add(jLabel53);
        jLabel53.setBounds(20, 650, 130, 16);
        jFrame4.getContentPane().add(jTextField24);
        jTextField24.setBounds(180, 610, 140, 30);

        jTextField25.setEditable(false);
        jFrame4.getContentPane().add(jTextField25);
        jTextField25.setBounds(180, 650, 170, 30);

        jButton8.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jButton8);
        jButton8.setBounds(260, 700, 230, 50);

        jButton11.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jButton11.setText("Continue");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jButton11);
        jButton11.setBounds(10, 700, 230, 50);

        jButton12.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jButton12.setText("Exit");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jButton12);
        jButton12.setBounds(520, 700, 190, 50);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("Show plans");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jButton5);
        jButton5.setBounds(10, 90, 120, 25);

        jTextField18.setEditable(false);
        jFrame4.getContentPane().add(jTextField18);
        jTextField18.setBounds(420, 500, 290, 30);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("New plan Details");
        jFrame4.getContentPane().add(jLabel31);
        jLabel31.setBounds(18, 570, 140, 17);

        jButton21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton21.setText("Proceed");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jButton21);
        jButton21.setBounds(620, 380, 110, 30);

        jLabel56.setText("Enter fname");
        jFrame4.getContentPane().add(jLabel56);
        jLabel56.setBounds(260, 390, 70, 16);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DATE", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jFrame4.getContentPane().add(jComboBox8);
        jComboBox8.setBounds(340, 382, 80, 30);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MONTH", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jFrame4.getContentPane().add(jComboBox9);
        jComboBox9.setBounds(420, 382, 80, 30);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YEAR", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010" }));
        jFrame4.getContentPane().add(jComboBox10);
        jComboBox10.setBounds(500, 382, 100, 30);

        jFrame7.setMinimumSize(new java.awt.Dimension(767, 711));
        jFrame7.getContentPane().setLayout(null);

        jLabel54.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel54.setText("Welcome to the Trends Section");
        jFrame7.getContentPane().add(jLabel54);
        jLabel54.setBounds(40, 10, 670, 60);

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel55.setText("Select the category");
        jFrame7.getContentPane().add(jLabel55);
        jLabel55.setBounds(30, 100, 140, 17);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton4.setText("The plan most preferred by users in each company");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jFrame7.getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(20, 140, 400, 25);

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton5.setText("The best plan based on age group");
        jFrame7.getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(20, 170, 290, 25);

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton7.setText("The company preffered the most");
        jFrame7.getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(20, 260, 300, 25);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELCT THE AGE GROUP", "Below 20", "20 to 40", "Above 40" }));
        jFrame7.getContentPane().add(jComboBox7);
        jComboBox7.setBounds(80, 220, 190, 22);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Company", "Plan ID", "Plan Description", "Count"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable3);

        jFrame7.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 330, 690, 220);

        jButton22.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jButton22.setText("Show Result");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jFrame7.getContentPane().add(jButton22);
        jButton22.setBounds(40, 580, 230, 60);

        jButton23.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jButton23.setText("Back");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jFrame7.getContentPane().add(jButton23);
        jButton23.setBounds(310, 580, 150, 60);

        jButton24.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jButton24.setText("Exit");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jFrame7.getContentPane().add(jButton24);
        jButton24.setBounds(500, 580, 150, 60);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(659, 564));
        setMinimumSize(new java.awt.Dimension(659, 564));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Telecom Network Analysis");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 140, 530, 60);

        jButton1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 36)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 300, 360, 60);

        jButton2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 36)); // NOI18N
        jButton2.setText("Sigh Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 400, 360, 60);

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 2, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 40, 190, 40);

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 2, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("to");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 90, 50, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shyam Kaushik\\Pictures\\backgroung\\dark bg with stars.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 660, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jFrame1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jFrame2.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        setVisible(true);
        jFrame1.setVisible(false);
        jTextField1.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        setVisible(true);
        jFrame2.setVisible(false);
        jTextField2.setText("");
        jTextField4.setText("");
        jTextField21.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jPasswordField2.setText("");
        jPasswordField3.setText("");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        username = jTextField1.getText();
        pswd = jPasswordField1.getText();
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            Statement stmt = (Statement)conn.createStatement();
            String query = "select * from login_tbl where username = '"+username+"';";
            ResultSet rs = stmt.executeQuery(query);
            if(rs.next())
            {
                //name = rs.getString("mem_name");
                username1 = rs.getString("username");
                pswd1 = rs.getString("pswd");
            }
            if(username.equals("") || pswd.equals(""))
            {
                JOptionPane.showMessageDialog(null,"Please enter the username and password");
            }
            else if(pswd.equals(pswd1) && username.equals(username1))
            {
                jFrame3.setVisible(true);
                jFrame1.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Please enter correct email and password");
                jTextField1.setText("");
                jPasswordField1.setText("");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        fname = jTextField2.getText();
        lname = jTextField4.getText();
        ssn = jTextField21.getText();
        email = jTextField5.getText();
        password = jPasswordField2.getText();
        cpassword = jPasswordField3.getText();
        phno = jTextField6.getText();
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            Statement stmt = (Statement)conn.createStatement();
            String query = "Insert into user_detail values('"+fname+"','"+lname+"',"+ssn+",'"+email+"','"+password+"',"+phno+");";
            //stmt.executeUpdate(query);
            
            Statement stm = (Statement)conn.createStatement();
            String query1 = "Insert into login_tbl values('"+email+"','"+password+"');";
            //stm.executeUpdate(query1);
            
            if(fname.isEmpty() || lname.isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Please fill all the NAME");
            }
            else if(email.isEmpty())
            {
                JOptionPane.showMessageDialog(null,"FILL THE EMAIL ADDRESS");
            }
            else if(password.isEmpty())
            {
                JOptionPane.showMessageDialog(null,"FILL THE PASSWORD");
            }
            else if(cpassword.isEmpty())
            {
                JOptionPane.showMessageDialog(null,"FILL THE CONFIRM PASSWORD");
            }
            else if(!password.equals(cpassword))
            {
                JOptionPane.showMessageDialog(null,"Password dosent match");
            }
            else if(ssn.isEmpty() || ssn.length()<8)
            {
                JOptionPane.showMessageDialog(null,"Incorrect SSN entered");
            }
            else if(phno.isEmpty())
            {
                JOptionPane.showMessageDialog(null,"FILL THE PHONE NUMBER");
            }
            else
            {
                
                stmt.executeUpdate(query);
                stm.executeUpdate(query1);
                JOptionPane.showMessageDialog(null,"You have been registered successfully");
                jFrame1.setVisible(true);
                jFrame2.setVisible(false);
                
                jTextField2.setText("");
                jTextField4.setText("");
                jTextField21.setText("");
                jTextField5.setText("");
                jPasswordField2.setText("");
                jPasswordField3.setText("");
                jTextField6.setText("");
                
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"LOGGING OUT\nCYA :)");
        jFrame3.setVisible(false);
        jFrame1.setVisible(true);
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()==true)
        {
            jFrame5.setVisible(true);
            jFrame3.setVisible(false);
        }
        else if(jRadioButton2.isSelected()==true)
        {
            jFrame4.setVisible(true);
            jFrame3.setVisible(false);
        }
        else if(jRadioButton3.isSelected()==true)
        {
            jFrame7.setVisible(true);
            jFrame3.setVisible(false);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        
        fname = jTextField10.getText();
        lname = jTextField11.getText();
        plan_id = jTextField12.getText();
        if(fname.isEmpty() || lname.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"ENTER THE NAME CORRECTLY");
        }
        else if(plan_id.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"ENTER THE PLAN ID");
        }
        else
        {
            jFrame6.setVisible(true);
            jFrame5.setVisible(false);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        jFrame3.setVisible(true);
        jFrame5.setVisible(false);
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            Statement stmt = (Statement)conn.createStatement();
            //String company = "";
            //String company_name = "";
            if(jComboBox1.getSelectedIndex()==0)
            {
                JOptionPane.showMessageDialog(null,"please select a company");
            }
            else if(jComboBox1.getSelectedIndex()==1)
            {
                company = "airtel_plan";
                company_name = "Airtel";
            }
            else if(jComboBox1.getSelectedIndex()==2)
            {
                company = "jio_plan";
                company_name = "Jio";
            }
            else if(jComboBox1.getSelectedIndex()==3)
            {
                company = "voda_plan";
                company_name = "Vodaphone";
            }
            else if(jComboBox1.getSelectedIndex()==4)
            {
                company = "idea_plan";
                company_name = "Idea";
            }
            else if(jComboBox1.getSelectedIndex()==5)
            {
                company = "docomo_plan";
                company_name = "Docomo";
            }
            
            String query = "select * from "+company+";";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next())
            {
                int pid = Integer.parseInt(rs.getString("plan_id"));
                String pname = rs.getString("pack_name");
                double price = Double.parseDouble(rs.getString("price"));
                String fup = rs.getString("fup");
                String upload = rs.getString("upload");
                String download = rs.getString("download");
                
                model.addRow(new Object[]{pid,pname,price,fup,upload,download});
            }
            jTextField13.setText(company_name);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        add1 = jTextField14.getText();
        add2 = jTextField15.getText();
        add3 = jTextField16.getText();
        pincode = jTextField17.getText();
        
        altphno = jTextField3.getText();
        email_add = jTextField20.getText();
        
        if(jComboBox6.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null,"Please select the CITY");
        }
        for(int i=1;i<=12;i++)
        {
            if(jComboBox6.getSelectedIndex()==i)
            {
                city = (String)jComboBox6.getSelectedItem();
            }
        }
        if(jComboBox3.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null,"Please fill in the DATE");
        }
        if(jComboBox4.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null,"Please fill in the MONTH");
        }
        if(jComboBox5.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null,"Please fill in the YEAR");
        }
        for(int i=1;i<=31;i++)
        {
            if(jComboBox3.getSelectedIndex()==i)
            {
                date = (String)jComboBox3.getSelectedItem();
            }
        }
        for(int i=1;i<=12;i++)
        {
            if(jComboBox4.getSelectedIndex()==i)
            {
                month = (String)jComboBox4.getSelectedItem();
            }
        }
        for(int i=1;i<=41;i++)
        {
            if(jComboBox5.getSelectedIndex()==i)
            {
                year = (String)jComboBox5.getSelectedItem();
            }
        }

        Random rand = new Random();
        uid = rand.nextInt(1000);
        suid = Integer.toString(uid);
        
        if(add1.isEmpty() || add2.isEmpty() ||add3.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"address line cannot be left blank");
            jTextField14.setText("");
            jTextField15.setText("");
            jTextField16.setText("");
        }
        else if(pincode.isEmpty() || pincode.length()<6 || pincode.length()>6)
        {
            JOptionPane.showMessageDialog(null,"Enter Valid pincode");
            jTextField17.setText("");
        }
        else if(altphno.isEmpty() || altphno.length() < 10 || altphno.length() > 10)
        {
            JOptionPane.showMessageDialog(null,"Enter Valid phone number");
            jTextField20.setText("");
        }
        else
        {
            try
            {
                Class.forName("java.sql.DriverManager");
                Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
                Statement stmt = (Statement)conn.createStatement();
                String query = "insert into sim_users values("+suid+",'"+fname+"','"+lname+"',"+plan_id+",'"+company_name+"');";
                Statement stm = (Statement)conn.createStatement();
                String query1 = "insert into sim_user_detail values("+suid+",'"+add1+"','"+add2+"','"+add3+"',"+pincode+","+altphno+",'"+email_add+"','"+year+"-"+month+"-"+date+"');";
                stmt.executeUpdate(query);
                stm.executeUpdate(query1);
                JOptionPane.showMessageDialog(null,"YOUR USER_ID IS: "+uid+"\nREMEMBER THE UID FOR FURTHER REFERRENCES");
                JOptionPane.showMessageDialog(null,"SUCCESSFULLY REGISTERED\nCONTINUE EXPLORING");
                jFrame3.setVisible(true);
                jFrame6.setVisible(false);
                jTextField14.setText("");
                jTextField15.setText("");
                jTextField16.setText("");
                jTextField17.setText("");
                jTextField3.setText("");
                jTextField20.setText("");
                jTextField14.setText("");
                jTextField15.setText("");
                jTextField16.setText("");
                jTextField17.setText("");
                jTextField3.setText("");
                jTextField20.setText("");
                jFrame3.setVisible(true);
                jFrame5.setVisible(false);
                jTextField10.setText("");
                jTextField11.setText("");
                jTextField12.setText("");
                jTextField13.setText("");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        jFrame5.setVisible(true);
        jTextField14.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField3.setText("");
        jTextField20.setText("");
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            Statement stmt = (Statement)conn.createStatement();
            //String company = "";
            //String company_name = "";
            if(jComboBox2.getSelectedIndex()==0)
            {
                JOptionPane.showMessageDialog(null,"please select a company");
            }
            else if(jComboBox2.getSelectedIndex()==1)
            {
                company = "airtel_plan";
                company_name = "Airtel";
            }
            else if(jComboBox2.getSelectedIndex()==2)
            {
                company = "jio_plan";
                company_name = "Jio";
            }
            else if(jComboBox2.getSelectedIndex()==3)
            {
                company = "voda_plan";
                company_name = "Vodaphone";
            }
            else if(jComboBox2.getSelectedIndex()==4)
            {
                company = "idea_plan";
                company_name = "Idea";
            }
            else if(jComboBox2.getSelectedIndex()==5)
            {
                company = "docomo_plan";
                company_name = "Docomo";
            }
            
            String query = "select * from "+company+";";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next())
            {
                int pid = Integer.parseInt(rs.getString("plan_id"));
                String pname = rs.getString("pack_name");
                double price = Double.parseDouble(rs.getString("price"));
                String fup = rs.getString("fup");
                String upload = rs.getString("upload");
                String download = rs.getString("download");
                
                model.addRow(new Object[]{pid,pname,price,fup,upload,download});
            }
            jTextField25.setText(company_name);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String d,m,y;
        plan_id = jTextField24.getText();
        company_name = jTextField25.getText();
        if(jComboBox3.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null,"Please fill in the DATE");
        }
        if(jComboBox4.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null,"Please fill in the MONTH");
        }
        if(jComboBox5.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null,"Please fill in the YEAR");
        }
        for(int i=1;i<=31;i++)
        {
            if(jComboBox3.getSelectedIndex()==i)
            {
                date = (String)jComboBox3.getSelectedItem();
            }
        }
        for(int i=1;i<=12;i++)
        {
            if(jComboBox4.getSelectedIndex()==i)
            {
                month = (String)jComboBox4.getSelectedItem();
            }
        }
        for(int i=1;i<=41;i++)
        {
            if(jComboBox5.getSelectedIndex()==i)
            {
                year = (String)jComboBox5.getSelectedItem();
            }
        }
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            Statement stmt = (Statement)conn.createStatement();
            /*String query1 = "select year(DOB) from sim_user_detail where uid = "+suid+";";
            ResultSet rs = stmt.executeQuery(query1);
            while(rs.next());
            {
                y = rs.
            }*/
            String query = "update sim_users set plan_id = "+plan_id+", service_provide = '"+company_name+"' where uid = "+suid+";";
            if(plan_id.isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Enter the new PLAN ID");
            }
            else
            {
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(null,"Plan changed successfully");
                jTextField7.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
                jTextField22.setText("");
                jTextField18.setText("");
                jTextField24.setText("");
                jTextField25.setText("");
                jFrame3.setVisible(true);
                jFrame4.setVisible(false);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        uid = Integer.parseInt(jTextField7.getText());
        suid = Integer.toString(uid);
        
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            Statement stmt = (Statement)conn.createStatement();
            String query = "select * from sim_users where uid = "+suid+";";
            ResultSet rs = stmt.executeQuery(query);
            if(rs.next())
            {
                //name = rs.getString("mem_name");
                fname = rs.getString("fname");
                lname = rs.getString("lname");
                plan_id = rs.getString("plan_id");
                company_name1 = rs.getString("service_provide");
            }
            jTextField8.setText(fname);
            jTextField9.setText(lname);
            jTextField22.setText(plan_id);
            Statement stm = (Statement)conn.createStatement();
            
            if(company_name1.equals("Airtel"))
                company1 = "airtel_plan";
            else if(company_name1.equals("Jio"))
                company1 = "jio_plan";
            else if(company_name1.equals("Vodaphone"))
                company1 = "voda_plan";
            else if(company_name1.equals("Idea"))
                company1 = "idea_plan";
            else if(company_name1.equals("Docomo"))
                company1 = "docomo_plan";
            
            String query1 = "select * from "+company1+" where plan_id = "+plan_id+";";
            ResultSet rs1 = stm.executeQuery(query1);
            if(rs1.next())
            {
                pack_name = rs1.getString("pack_name");
            }
            jTextField18.setText(pack_name);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable3.getModel();
        model.setRowCount(0);
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            Statement stmt = (Statement)conn.createStatement();
            String query = "";
            String comp = "";
            String compname = "";
            String pid = "";
            String pname = "";
            String c = "";
            
            int r,q;
            if(jRadioButton4.isSelected()==true)
            {
                query = "select plan from display_airtel where number = (select max(number) from display_airtel);";
                ResultSet rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    comp =  "Airtel";
                    pid = rs.getString("plan");
                    
                }
                query = "select * from airtel_plan where plan_id = "+pid+";";
                ResultSet rs5 = stmt.executeQuery(query);
                while(rs5.next())
                {
                    pname = rs5.getString("pack_name");
                }
                model.addRow(new Object[]{comp,pid,pname});
                query = "select plan from display_jio where number = (select max(number) from display_jio);";
                ResultSet rs1 = stmt.executeQuery(query);
                while(rs1.next())
                {
                    comp = "Jio";
                    pid = rs1.getString("plan");
                    
                }
                query = "select * from jio_plan where plan_id = "+pid+";";
                ResultSet rs6 = stmt.executeQuery(query);
                while(rs6.next())
                {
                    pname = rs6.getString("pack_name");
                }
                model.addRow(new Object[]{comp,pid,pname});
                query = "select plan from display_voda where number = (select max(number) from display_voda);";
                ResultSet rs2 = stmt.executeQuery(query);
                while(rs2.next())
                {
                    comp = "Vodaphone";
                    pid = rs2.getString("plan");
                    
                }
                query = "select * from voda_plan where plan_id = "+pid+";";
                ResultSet rs7 = stmt.executeQuery(query);
                while(rs7.next())
                {
                    pname = rs7.getString("pack_name");
                }
                model.addRow(new Object[]{comp,pid,pname});
                query = "select plan from display_idea where number = (select max(number) from display_idea);";
                ResultSet rs3 = stmt.executeQuery(query);
                while(rs3.next())
                {
                    comp = "Idea";
                    pid = rs3.getString("plan");
                    
                }
                query = "select * from idea_plan where plan_id = "+pid+";";
                ResultSet rs8 = stmt.executeQuery(query);
                while(rs8.next())
                {
                    pname = rs8.getString("pack_name");
                }
                model.addRow(new Object[]{comp,pid,pname});
                query = "select plan from display_docomo where number = (select max(number) from display_docomo);";
                ResultSet rs4 = stmt.executeQuery(query);
                while(rs4.next())
                {
                    comp = "Docomo";
                    pid = rs4.getString("plan");
                    
                }
                query = "select * from docomo_plan where plan_id = "+pid+";";
                ResultSet rs9 = stmt.executeQuery(query);
                while(rs9.next())
                {
                    pname = rs9.getString("pack_name");
                }
                model.addRow(new Object[]{comp,pid,pname});
            }
            else if(jRadioButton5.isSelected()==true)
            {
                if(jComboBox7.getSelectedIndex()==0)
                {
                    JOptionPane.showMessageDialog(null,"Select a valid AGE GROUP");
                }
                else if(jComboBox7.getSelectedIndex()==1)
                {
                    query = "select * from display_age_20;";
                    ResultSet rs = stmt.executeQuery(query);
                    while(rs.next())
                    {
                        String plan = rs.getString("plan");
                        String count = rs.getString("number");
                        
                        int val = Integer.parseInt(plan);
                        r = val/100;
                        if(r==1)
                        {
                            comp = "Airtel";
                            model.addRow(new Object[]{comp,plan,compname,count});
                        }
                        else if(r==2)
                        {
                            comp = "Jio";
                            model.addRow(new Object[]{comp,plan,compname,count});
                        }
                        else if(r==3)
                        {
                            comp = "Vodafone";
                            model.addRow(new Object[]{comp,plan,compname,count});
                        }
                        else if(r==4)
                        {
                            comp = "Idea";
                            model.addRow(new Object[]{comp,plan,compname,count});
                        }
                        else
                        {
                            comp = "Docomo";
                            model.addRow(new Object[]{comp,plan,compname,count});
                        }    
                    }
                }
                
                else if(jComboBox7.getSelectedIndex()==2)
                {
                    query = "select * from display_age_40;";
                    ResultSet rs = stmt.executeQuery(query);
                    while(rs.next())
                    {
                        String plan = rs.getString("plan");
                        String count = rs.getString("number");
                        
                        int val = Integer.parseInt(plan);
                        r = val/100;
                        if(r==1)
                        {
                            comp = "Airtel";
                            model.addRow(new Object[]{comp,plan,compname,count});
                        }
                        else if(r==2)
                        {
                            comp = "Jio";
                            model.addRow(new Object[]{comp,plan,compname,count});
                        }
                        else if(r==3)
                        {
                            comp = "Vodafone";
                            model.addRow(new Object[]{comp,plan,compname,count});
                        }
                        else if(r==4)
                        {
                            comp = "Idea";
                            model.addRow(new Object[]{comp,plan,compname,count});
                        }
                        else
                        {
                            comp = "Docomo";
                            model.addRow(new Object[]{comp,plan,compname,count});
                        }     
                    }
                }
                else if(jComboBox7.getSelectedIndex()==3)
                {
                    query = "select * from display_age_40p;";
                    ResultSet rs = stmt.executeQuery(query);
                    while(rs.next())
                    {
                        String plan = rs.getString("plan");
                        String count = rs.getString("number");
                        
                        int val = Integer.parseInt(plan);
                        r = val/100;
                        if(r==1)
                        {
                            comp = "Airtel";
                            model.addRow(new Object[]{comp,plan,compname,count});
                        }
                        else if(r==2)
                        {
                            comp = "Jio";
                            model.addRow(new Object[]{comp,plan,compname,count});
                        }
                        else if(r==3)
                        {
                            comp = "Vodafone";
                            model.addRow(new Object[]{comp,plan,compname,count});
                        }
                        else if(r==4)
                        {
                            comp = "Idea";
                            model.addRow(new Object[]{comp,plan,compname,count});
                        }
                        else
                        {
                            comp = "Docomo";
                            model.addRow(new Object[]{comp,plan,compname,count});
                        }     
                    }
                }
            }
            else if(jRadioButton7.isSelected()==true)
            {
                query = "select service_provide, count(service_provide) from sim_users group by service_provide;";
                ResultSet rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    comp = rs.getString("service_provide");
                    c = rs.getString("count(service_provide)");
                    model.addRow(new Object[]{comp,pid,compname,c});
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        jFrame7.setVisible(false);
        jFrame3.setVisible(true);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jFrame4.setVisible(false);
        jFrame3.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telecom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telecom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telecom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telecom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telecom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JFrame jFrame6;
    private javax.swing.JFrame jFrame7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
